# Generated by Django 4.1.1 on 2022-10-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_hospitaldonation_delete_donation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_group", models.CharField(max_length=50)),
                ("time_of_use", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.hospital"
                    ),
                ),
            ],
        ),
    ]
