# Generated by Django 4.1.1 on 2022-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_donationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationrequest",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A RhD positive (A+)", "A RhD positive (A+)"),
                    ("A RhD negative (A-)", "A RhD negative (A-)"),
                    ("B RhD positive (B+)", "B RhD positive (B+)"),
                    ("B RhD negative (B-)", "B RhD negative (B-)"),
                    ("O RhD positive (O+)", "O RhD positive (O+)"),
                    ("O RhD negative (O-)", "O RhD negative (O-)"),
                    ("AB RhD positive (AB+)", "AB RhD positive (AB+)"),
                    ("AB RhD negative (AB-)", "AB RhD negative (AB-)"),
                ],
                max_length=50,
            ),
        ),
    ]
