# Generated by Django 4.1.1 on 2022-10-14 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="aadhar_no",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(70),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="blood_group",
            field=models.TextField(
                choices=[
                    ("A RhD positive (A+)", "A RhD positive (A+)"),
                    ("A RhD negative (A-)", "A RhD negative (A-)"),
                    ("B RhD positive (B+)", "B RhD positive (B+)"),
                    ("B RhD negative (B-)", "B RhD negative (B-)"),
                    ("O RhD positive (O+)", "O RhD positive (O+)"),
                    ("O RhD negative (O-)", "O RhD negative (O-)"),
                    ("AB RhD positive (AB+)", "AB RhD positive (AB+)"),
                    ("AB RhD negative (AB-)", "AB RhD negative (AB-)"),
                ],
                null=True,
            ),
        ),
    ]
